### PR TITLE
Integrate react-native-module-template properly into the monorepo

### PR DESCRIPTION
**Pull request by shirakaba**
Right now `react-native-module-template` is not integrated properly into the monorepo:

- it's not sharing dependencies, so it has a conflicting version of eslint and typescript with the other apps/packages and requires multiple `yarn install` actions in different directories to set up;
- it doesn't have tsconfig path aliases to all the other packages in the monorepo, so it can't use them as in-development libraries;
- there are no nx shortcuts for it

Hopefully this should fix all that, except for the last point, as I don't really know what shortcuts we want to set up.

One thing I should caution is that the [react-native-module-template](https://github.com/demchenkoalex/react-native-module-template) that `react-native-module-template` was generated from is a bit out of date (uses RN 0.67.0 when the latest is 0.69.x). I'm not a huge fan of that template in general, particularly in the context of this monorepo - ideally we'd split the examples and libraries out into further demos and packages. But ultimately it works enough to get moving, so I'm happy to just move on and focus on the bridge work anyway.

### CODE REVIEW

**Comment by ammarahm-ed** [comment]
Hey @shirakaba thanks for the PR. I have two questions.

1. The `react-native-module-test` is a library with an example inside it. Is apps/ the best place for it?

2. It's also inked with `packages/react-native/react` folder since it needs to be compiled along with react into a single aar file. 

The Library is using an outdated version agreed. But we can update it eventually as we get some parts of the bridge working. For now I just needed something to get moving. It would be best to use react-native-builder-bob eventually.

**Comment by shirakaba** [comment]
A note to myself. Originally I added the app and package manually, updating each of the nx config files manually. But I just tried using `npm run add` to try adding a package the official way and so here's a record of all the things that got changed which I'll have to account for (and some of which I may undo):

```sh
➜  nativescript-magic-spells git:(repo-restructure) npm run add

> plugins@0.0.0 add
> nx g @nativescript/plugin-tools:add-package


>  NX  Generating @nativescript/plugin-tools:add-package

✔ What should the new package be named? · react-native-module-test
✔ Should it use the npm scope of the workspace? 'Y' is the most common. This is the difference between, for example @nativescript/camera vs. nativescript-camera. If you choose 'N' here, be sure you have specified the full npm name you would like to use during publishing. (Y/n) · true

Updating "apps/demo"
Updating "apps/demo-angular"
Updating shared demo code in "tools/demo"
"@@ammarahm-ed/react-native-module-test" created and added to all demo apps. Ready to develop!
CREATE packages/react-native-module-test/README.md
CREATE packages/react-native-module-test/.eslintrc.json
CREATE packages/react-native-module-test/common.ts
CREATE packages/react-native-module-test/index.android.ts
CREATE packages/react-native-module-test/index.d.ts
CREATE packages/react-native-module-test/index.ios.ts
CREATE packages/react-native-module-test/package.json
CREATE packages/react-native-module-test/references.d.ts
CREATE packages/react-native-module-test/tsconfig.json
CREATE packages/react-native-module-test/project.json
UPDATE workspace.json
UPDATE tools/workspace-scripts.js
UPDATE README.md
UPDATE tsconfig.base.json
CREATE apps/demo/src/plugin-demos/react-native-module-test.ts
CREATE apps/demo/src/plugin-demos/react-native-module-test.xml
UPDATE apps/demo/src/main-page.xml
UPDATE apps/demo/package.json
CREATE apps/demo-angular/src/plugin-demos/react-native-module-test.component.html
CREATE apps/demo-angular/src/plugin-demos/react-native-module-test.component.ts
CREATE apps/demo-angular/src/plugin-demos/react-native-module-test.module.ts
UPDATE apps/demo-angular/src/home.component.ts
UPDATE apps/demo-angular/src/app-routing.module.ts
UPDATE apps/demo-angular/package.json
CREATE tools/demo/react-native-module-test/index.ts
UPDATE tools/demo/index.ts
```

**Comment by ammarahm-ed** [comment]
I really like how you keep record of everything as you make changes. I will have to learn that from you probably.

**Comment by shirakaba** [comment]
Think I've sunk far too much time into this and am going to give up on integrating React Native properly into the monorepo at this point.

React Native is simply atrocious for monorepos. I have been peppering the build code of Nx, Metro, Haste, and the RN CLI with console logs for three days now and I am honestly giving up at this point. I've tried just about everything, including `patch-package`, unhoisting dependencies, and studying the RN nx template, and every time I get a step further, some new absolutely unfathomable error crops up.

The whole point of monorepo tooling is to make you move faster, but this has just exhausted me when I could have been building the bridge the whole time.

I'll leave the branch around in case anyone is feeling brave, but at this point I'm done with it.

The main problem about giving up on this is that I was unable to successfully install the repo in the first place, so I am going to be blocked on developing it either way. Maybe we could still pick bits out of this PR to at least make the NativeScript and RN align on the same dep version (linter, typescript), however, which might get me past the installation that I was failing on. Metro can't resolve symlinks, but maybe that doesn't matter for dev dependencies (e.g. if the demo app were to take some deps from the root node_modules instead). I'm really not sure.

**Comment by ammarahm-ed** [comment]
@shirakaba I agree, this has wasted a lot of time. Maybe we should move on with writing the bridge with the current structure on master branch. We can come back to this later when we have a working bridge and then find a proper solution. 

Right now what I do is, go into react-native-module-test dir and run `yarn` then go into example folder & run `yarn` again. That's all and things are working for me without issues. I am not sure why you are getting eslint errors.

**Comment by shirakaba** [comment]
I've given this a try and this time it didn't fail (perhaps because I was using Node 16 instead of Node 18; who knows):

```sh
git clone git@github.com:ammarahm-ed/nativescript-magic-spells.git
yarn setup && cd react-native-module-test && yarn && cd example && yarn 
```

Will take a break for now (or all of today), but would be nice if that's me unblocked at this point.

**Comment by ammarahm-ed** [comment]
@shirakaba I fixed the build on iOS on the master branch so that the example app will just run. make sure to pull when you work on this again.

**Comment by ammarahm-ed** [comment]
Fixed & merged.

**Pull request merged**
